version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: team26
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: team26user
      MYSQL_PASSWORD: team26
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: team26-csticaret
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "9191:9191"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/e-commerce?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: team26
    networks:
      - spring-mysql-network

volumes:
  mysql-data:

networks:
  spring-mysql-network:
    driver: bridge